const projects = [
    {
        nameDE : 'Newsletter Anmeldung',
        nameEN : 'Newsletter Registration',
        image : '../../img/newsletter.PNG',
        alt: 'newsletter login',
        languages : 'HTML - CSS',
        descriptionDE : 'Ein Newsletter-Layout mit verschiedenen Eingabemöglichkeiten sowie verschiedenen Animationen. In diesem Projekt wurden die Möglichkeiten mit Forms vertieft und umgesetzt.',
        descriptionEN : 'A newsletter layout with various input options and the first attempts with animations. In this project, the possible uses of the input fields were learned and implemented.',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-3',
        linkPage : 'https://dominicrehm.github.io/newsletter/',
    },
    {
        nameDE : 'Interaktive Photogallerie',
        nameEN : 'Interactive Photogallery',
        image : '../../img/photogallery.PNG',
        alt: 'interactive photogallery',
        languages : 'HTML - CSS - JQuery',
        descriptionDE : 'In diesem Projekt wurde mit JQuery eine interaktive Photogallerie erstellt. Der Besucher hat die Möglichkeit die Bilder per Klick zu vergrößern.',
        descriptionEN : 'In this project, an interactive photo gallery was created with JQuery. The visitor has the possibility to enlarge the pictures with a click.',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-5',
        linkPage : 'https://dominicrehm.github.io/photogallery/',
    },
    {
        nameDE : 'Galgenmännchen-Spiel',
        nameEN : 'Wheel of Success',
        image : '../../img/wheelOfSuccess.PNG',
        alt: 'wheel of success',
        languages : 'HTML - CSS - JavaScript',
        descriptionDE : 'Versuche dein Glück und errate die Wörter. Wirst du gewinnen oder verlieren? Lass dich mit JavaScript unterhalten!',
        descriptionEN : 'Try your luck and guess the words. Are you going to win or lose? Let yourself be entertained with JavaScript!',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-6',
        linkPage : 'https://dominicrehm.github.io/gameapp/',
    },
    {
        nameDE : 'Back-End Dashboard',
        nameEN : 'Back-End Dashboard',
        image : '../../img/dashboard.PNG',
        alt: 'back-end dashboard',
        languages : 'HTML - CSS - JavaScript',
        descriptionDE : 'Ein Layout für ein Back-End Dashboard mit verschiedenen Möglichkeiten für die Auswertung der eigenen Seite.',
        descriptionEN : 'A layout for a back-end dashboard with various options for evaluating your own page.',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-7',
        linkPage : 'https://dominicrehm.github.io/dashboard/',
    },
    {
        nameDE : 'API Anbindung',
        nameEN : 'Working with API',
        image : '../../img/api.PNG',
        alt: 'api connection',
        languages : 'HTML - CSS - JavaScript',
        descriptionDE : 'Finde auf der Seite den passenden Mitarbeiter per Suchfunktion und rufe noch weitere Informationen per Klick auf.',
        descriptionEN : 'Find the right employee on the page using the search function and call up further information by clicking.',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-8',
        linkPage : 'https://dominicrehm.github.io/api/',
    }
];