const projects = [
    {
        nameDE : 'Newsletter Anmeldung',
        nameEN : 'Newsletter Registration',
        image : '../../img/newsletter.PNG',
        alt: 'newsletter login',
        link : 'Link',
        languages : 'HTML - CSS',
        descriptionDE : 'Ein Newsletter-Layout mit verschiedenen Eingabemöglichkeiten sowie verschiedenen Animationen.',
        descriptionEN : 'Description',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-3',
        linkPage : 'https://dominicrehm.github.io/newsletter/',
    },
    {
        nameDE : 'Interaktive Photogallerie',
        nameEN : 'Interactive Photogallery',
        image : '../../img/photogallery.PNG',
        alt: 'interactive photogallery',
        link : 'Link',
        languages : 'HTML - CSS - JQuery',
        descriptionDE : 'Description',
        descriptionEN : 'Description',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-5',
        linkPage : 'https://dominicrehm.github.io/photogallery/',
    },
    {
        nameDE : 'Galgenmännchen-Spiel',
        nameEN : 'Wheel of Success',
        image : '../../img/wheelOfSuccess.PNG',
        alt: 'wheel of success',
        link : 'Link',
        languages : 'HTML - CSS - JavaScript',
        descriptionDE : 'Description',
        descriptionEN : 'Description',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-6',
        linkPage : '../projects/techdegree-project-6/index.html',
    },
    {
        nameDE : 'Back-End Dashboard',
        nameEN : 'Back-End Dashboard',
        image : '../../img/dashboard.PNG',
        alt: 'back-end dashboard',
        link : 'Link',
        languages : 'HTML - CSS - JavaScript',
        descriptionDE : 'Description',
        descriptionEN : 'Description',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-7',
        linkPage : '../projects/techdegree-project-7/index.html',
    },
    {
        nameDE : 'API Anbindung',
        nameEN : 'Working with API',
        image : '../../img/api.PNG',
        alt: 'api connection',
        link : 'Link',
        languages : 'HTML - CSS - JavaScript',
        descriptionDE : 'Description',
        descriptionEN : 'Description',
        linkGit : 'https://github.com/DominicRehm/techdegree-project-8',
        linkPage : '../projects/techdegree-project-8/index.html',
    }
];